#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_shadow float
yabai -m config window_placement second_child

# Padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# Mouse
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Unmanaged apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Preferences$" manage=off
